/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Silla;
import java.awt.GridLayout;

/**
 *
 * @author kuroy
 */
public class formSala extends javax.swing.JPanel {
    private Button buttons[][][];
    public Thread threads[][][];
    /**
     * Creates new form formSala
     */
    public formSala() {
        initComponents();
        
    }
    
    /**
     * Añade los listener a sus componentes
     * @param e 
     */
    public void initListener(java.awt.event.ActionListener e){     
        btnCamb.addActionListener(e);
        btnCont.addActionListener(e);
        btnVolver.addActionListener(e);
    }
    
    /**
     * Inicializa la sala con cantidad de peliculas actualiza y el numero de 
     * filas y columnas en el arreglo tridimensional
     * @param ids
     * @param filas
     * @param columnas 
     */
    public void initSalas(Integer ids, Integer filas, Integer columnas){
        panelButton.setLayout(new GridLayout(filas, columnas));
        Character letra[] = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'};
        Integer numero = 8;
        
        threads = new Thread[ids][filas][columnas];              
        buttons = new Button[ids][filas][columnas];
        
        for (int i = 0; i < buttons.length; i++) {
            for (int j = buttons[i].length-1; j >= 0 ; j--) {
                for(int k=0; k<buttons[i][j].length; k++){
                    buttons[i][j][k] = new Button(numero+"-"+letra[k]);
                    threads[i][j][k] = new Thread(buttons[i][j][k]);
                    threads[i][j][k].start();                    
                }
                numero--;
            }
            numero = 8;
        }
    }

    public Button[][][] getButtons() {
        return buttons;
    }
    
    /**
     * Muestra la sala de la id de pelicula recibida
     * @param id 
     */
    public void mostrarSala(Integer id){
        panelButton.removeAll();
        for (int i = 0; i < buttons[id].length; i++) {
            for (int j = 0; j < buttons[id][i].length; j++) {
                panelButton.add(buttons[id][i][j]);
            }
        }
    }
    
    /**
     * Hace intermitente el button que simula la silla que le toco al espectador
     * aleatoriamente
     * @param id
     * @param x 
     */
    public void intermitente(Integer id, Integer x[]){
        buttons[id][x[0]][x[1]].activar();
        
    }
    
    /**
     * Limpia una sala respecto a la id de pelicula recibida
     * @param id 
     */
    public void clear(Integer id){
        for (int i = 0; i < buttons[id].length; i++) {
            for(Integer j=0; j<buttons[id][i].length; j++){
                buttons[id][i][j].desactivar();
            }
        }
    }
    
    /*
        PARA PRUEBA AUTOMATICA
    */
    public void llenarSalas(Silla sillas[][][]){
        for (Integer i = 0; i < sillas.length; i++) {
            for (Integer j = 0; j < sillas[i].length; j++) {
                for (Integer k = 0; k < sillas[i][j].length; k++) {
                    if(!sillas[i][j][k].isEmpty()){
                        buttons[i][j][k].selected();
                    }
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelButton = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnCont = new javax.swing.JButton();
        btnCamb = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(515, 268));

        panelButton.setBackground(new java.awt.Color(0, 0, 0));
        panelButton.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sala", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnCont.setBackground(new java.awt.Color(255, 255, 255));
        btnCont.setForeground(new java.awt.Color(0, 0, 0));
        btnCont.setText("Continuar");
        btnCont.setBorderPainted(false);
        btnCont.setFocusable(false);

        btnCamb.setBackground(new java.awt.Color(255, 255, 255));
        btnCamb.setForeground(new java.awt.Color(0, 0, 0));
        btnCamb.setText("Cambiar puesto");
        btnCamb.setBorderPainted(false);
        btnCamb.setFocusable(false);

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("Volver");
        btnVolver.setBorderPainted(false);
        btnVolver.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnCont)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCamb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnCont)
                .addComponent(btnCamb)
                .addComponent(btnVolver))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCamb;
    public javax.swing.JButton btnCont;
    public javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel panelButton;
    // End of variables declaration//GEN-END:variables
}
